services:
    changedetection-dev:
      image: logickee/changedetect
      
      volumes:
        - changedetection-data:/datastore
        - ./changedetectionio:/app/changedetectionio

      environment:
        - PYTHONDONTWRITEBYTECODE=1

      ports:
        - 5001:5000

    # changedetection:
    #   # image: ghcr.io/dgtlmoon/changedetection.io
    #   build: .
      
    #   volumes:
    #     - changedetection-data:/datastore
    #     - ./changedetectionio:/app/changedetectionio

    #   environment:
    #     - PYTHONDONTWRITEBYTECODE=1
      
    #   ports:
    #     - 5001:5001
    #   restart: unless-stopped

volumes:
  changedetection-data:

